# Generated by Django 2.2.7 on 2019-11-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0003_auto_20181108_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='jugador',
            name='consola',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='compania',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
    ]
